"""add pix_key to trainers

Revision ID: a6510fbff360
Revises: 
Create Date: 2026-04-12 22:31:25.667976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6510fbff360'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_key', sa.String(length=150), nullable=True, comment='Chave PIX do trainer para recebimento de mensalidades'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_column('pix_key')

    # ### end Alembic commands ###
